apiVersion: batch/v1
kind: Job
metadata:
  name: spotify-listen-together-postgresql-job
spec:
  template:
    spec:
      containers:
        - name: spotifylistentogetherpostgresql
          image: {{docker_registry_domain}}/spotifylistentogetherpostgresql:{{docker_image_version}}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
      restartPolicy: Never