apiVersion: batch/v1
kind: Job
metadata:
  name: spotify-listen-together-postgresql-job
spec:
  template:
    spec:
      containers:
        - name: spotifylistentogetherpostgresql
          image: localhost:5000/spotifylistentogetherpostgresql:{{TAG_NUMBER}}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
      restartPolicy: Never